### ISSUE TITLE
Feature Request: Touriquets

### ISSUE THREAD

**Issue by M3ales** [M3ales/MIRA_Vehicle_Medical#14]
## Stable

- Display the number of tourniquets on person, show as stable if > 1 is on a person.

**Comment by M3ales** [comment]
@GoldJohnKing Can you please add the Chinese Simplified Translation for `Tourniquets` when you're able, Thanks.

Commit: e9822bd1c40318156b9bc217d7072c8c0ea84aad

**Comment by GoldJohnKing** [comment]
> @GoldJohnKing Can you please add the Chinese Simplified Translation for `Tourniquets` when you're able, Thanks.
> 
> Commit: [e9822bd](https://github.com/M3ales/MIRA_Vehicle_Medical/commit/e9822bd1c40318156b9bc217d7072c8c0ea84aad)

Done, see #16 .
